In [1]:
import os
from flask import Flask, request, redirect, url_for, render_template
from werkzeug.utils import secure_filename
app = Flask(__name__)
from keras.models import load_model
#from keras.backend import set_session
from keras import backend as K
#from tensorflow.python.keras import backend as K
from tensorflow.compat.v1.keras import backend as K
from skimage.transform import resize
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

In [2]:
print("Loading model")
global sess
sess = tf.compat.v1.Session()
K.set_session(sess)
global graph
graph = tf.compat.v1.get_default_graph()

@app.route('/', methods=['GET','POST'])
def main_page():
    if request.method == 'POST':
        file = request.files['file']
        filename = secure_filename(file.filename)
        file.save(os.path.join('uploads', filename))
        return redirect(url_for('prediction', filename=filename))
    return render_template('index.html')

@app.route('/prediction/<filename>')
def prediction(filename):
    #Step 1
    my_image = plt.imread(os.path.join('uploads', filename))
    #Step 2
    my_image_re = resize(my_image, (224,224,3))
    
    #Step 3
    with graph.as_default():
        K.set_session(sess)
        model = load_model('leaf-cnn.h5')
        probabilities = model.predict(np.array( [my_image_re,] ))[0,:]
        print(probabilities)
#Step 4
    number_to_class = ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy']
      
    index = np.argsort(probabilities)
       
    predictions = {
       "class1":number_to_class[index[3]],
        "class2":number_to_class[index[2]],
        "prob1":probabilities[index[3]],
        "prob2":probabilities[index[2]],
      }
#Step 5
    return render_template('predict.html', predictions=predictions)
app.debug = False
app.run(host='localhost')

Loading model
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2021 20:22:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 20:22:35] "POST / HTTP/1.1" 302 -
C:\Users\User1\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
127.0.0.1 - - [29/Apr/2021 20:22:37] "GET /prediction/AppleScab3.JPG HTTP/1.1" 200 -


[9.9997842e-01 1.5488697e-05 4.0773730e-06 2.0080433e-06]


127.0.0.1 - - [29/Apr/2021 20:22:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 20:22:47] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 20:22:49] "GET /prediction/AppleCedarRust1.JPG HTTP/1.1" 200 -


[3.5531143e-06 6.4928472e-06 9.9998999e-01 2.4378311e-08]


127.0.0.1 - - [29/Apr/2021 20:24:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 20:25:02] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 20:25:06] "GET /prediction/AppleCedarRust2.JPG HTTP/1.1" 200 -


[8.4076376e-08 6.8996222e-08 9.9999988e-01 2.6040019e-09]


127.0.0.1 - - [29/Apr/2021 20:25:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 20:38:16] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 20:38:19] "GET /prediction/AppleCedarRust1.JPG HTTP/1.1" 200 -


[3.5531143e-06 6.4928472e-06 9.9998999e-01 2.4378311e-08]


127.0.0.1 - - [29/Apr/2021 20:38:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 20:38:35] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 20:38:39] "GET /prediction/CornCommonRust3.JPG HTTP/1.1" 200 -


[9.9962199e-01 3.4426209e-06 3.7456787e-04 7.3245707e-09]


127.0.0.1 - - [29/Apr/2021 20:38:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 21:34:44] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 21:34:48] "GET /prediction/TomatoHealthy4.JPG HTTP/1.1" 200 -


[9.9585658e-01 5.1579282e-05 4.3041233e-04 3.6614521e-03]


127.0.0.1 - - [29/Apr/2021 21:34:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 21:34:56] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 21:35:00] "GET /prediction/AppleCedarRust2.JPG HTTP/1.1" 200 -


[8.4076376e-08 6.8996222e-08 9.9999988e-01 2.6040019e-09]


127.0.0.1 - - [29/Apr/2021 21:35:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Apr/2021 21:35:10] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [29/Apr/2021 21:35:14] "GET /prediction/AppleScab3.JPG HTTP/1.1" 200 -


[9.9997842e-01 1.5488697e-05 4.0773730e-06 2.0080433e-06]


127.0.0.1 - - [29/Apr/2021 21:35:28] "GET / HTTP/1.1" 200 -
